apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx-pod
  type: LoadBalancer
  loadBalancerIP: ${IP_TO_SUBST}
  ports:
  - port: 30022
    name: ssh-svc-port
    targetPort: ssh-cont-port
    protocol: TCP
    nodePort: 30022
  - port: 80
    name: http-svc-port
    targetPort: http-cont-port
    protocol: TCP
    nodePort: 80
  - port: 443
    name: https-svc-port
    targetPort: https-cont-port
    protocol: TCP
    nodePort: 443

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 30022
          name: ssh-cont-port
        - containerPort: 80
          name: http-cont-port
        - containerPort: 443
          name: https-cont-port
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep sshd && pgrep nginx'
          initialDelaySeconds: 10
          periodSeconds: 5
