apiVersion: v1
kind: Service
metadata:
  name: wp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: wp-service
spec:
  selector:
    app: wp-pod
  type: LoadBalancer
  loadBalancerIP: ${IP_TO_SUBST}
  ports:
  - port: 5050
    name: wp-service-port
    targetPort: wp-cont-port
    protocol: TCP
    nodePort: 5050

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wp-deployment
spec:
  selector:
    matchLabels:
      app: wp-pod
  template:
    metadata:
      labels:
        app: wp-pod
    spec:
      containers:
      - name: wordpress
        image: e_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wp-cont-port
        env:
        - name: IP_MINIKUBE
          value: ${IP_TO_SUBST}
        - name: MYSQL_IP
          value: mysql-service
        volumeMounts:
        - name: wp-volume
          mountPath: /usr/share/webapps/wordpress/wp-content/
      volumes:
      - name: wp-volume
        hostPath:
          path: /tmp/wp_vol
