apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: grafana-service
spec:
  selector:
    app: grafana-pod
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
  ports:
  - port: 3000
    name: grafana-svc-port
    targetPort: grafana-port
    protocol: TCP
    nodePort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana-pod
  template:
    metadata:
      labels:
        app: grafana-pod
    spec:
      containers:
      - name: grafana
        image: e_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana-port
        env:
        - name: IP_MINIKUBE
          value: 172.17.0.2
        - name: INFLUXDB_URL
          value: http://influxdb-service:8086
