apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin-pod
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
  ports:
  - port: 5000
    name: phpmyadmin-svc-port
    targetPort: phpmyadmin-port
    protocol: TCP
    nodePort: 5000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin-pod
  template:
    metadata:
      labels:
        app: phpmyadmin-pod
    spec:
      containers:
      - name: phpmyadmin
        image: my_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
        env:
        - name: IP_MYSQL
          value: mysql-service
